#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the Common Development
# and Distribution License Version 1.0 (the "License").
#
# You can obtain a copy of the license at
# http://www.opensource.org/licenses/CDDL-1.0.  See the License for the
# specific language governing permissions and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each file and
# include the License file in a prominent location with the name LICENSE.CDDL.
# If applicable, add the following below this CDDL HEADER, with the fields
# enclosed by brackets "[]" replaced with your own identifying information:
#
#
# CDDL HEADER END
#

#
# Copyright (c) 2012, Mark R. Gilbert, CCFE Fusion Association.  All rights reserved.
#
# Contributors:
#    Mark R. Gilbert
#

#
#
#


# load all basic KIM make configuration
include ../Makefile.KIM_Config

# set model driver specific details
MODEL_DRIVER_NAME := model_driver_PF_cubic_splines__MD_620624592962_001
MODEL_NAME := model_Ta_PF_cubicsplines_derletnguyenmanhdudarev__MO_261274272789_001
SPECIES_001_NAME    := Ta
PARAM_FILE_001_NAME := model_Ta_PF_cubicsplines.params

# APPEND to compiler option flag lists
#FFLAGS   +=
#CFLAGS   +=
#CXXFLAGS +=
#LDFLAGS  +=

# load remaining KIM make configuration
include $(KIM_DIR)/$(builddir)/Makefile.ParameterizedModel
