# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can
# obtain one at http://mozilla.org/MPL/2.0/.

# load all basic KIM make configuration
include ../Makefile.KIM_Config

# set model specific details
MODEL_NAME := Pair_Johnson_Fe__MO_857282754307_002
MODEL_KIM_FILE := Pair_Johnson_Fe.kim
MODEL_INIT_FUNCTION_NAME := model_init

LOCALOBJ = Pair_Johnson_Fe.o

LOCALCLEAN =

# APPEND to compiler option flag lists
#FFLAGS   +=
#CFLAGS   +=
#CXXFLAGS +=
#LDFLAGS  +=

# load remaining KIM make configuration
include $(KIM_DIR)/$(builddir)/Makefile.Model
