#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the Common Development
# and Distribution License Version 1.0 (the "License").
#
# You can obtain a copy of the license at
# http://www.opensource.org/licenses/CDDL-1.0.  See the License for the
# specific language governing permissions and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each file and
# include the License file in a prominent location with the name LICENSE.CDDL.
# If applicable, add the following below this CDDL HEADER, with the fields
# enclosed by brackets "[]" replaced with your own identifying information:
#
# Portions Copyright (c) [yyyy] [name of copyright owner]. All rights reserved.
#
# CDDL HEADER END
#

#
# Copyright (c) 2012, Regents of the University of Minnesota.  All rights reserved.
#
# Contributors:
#    Ryan S. Elliott
#    Ellad B. Tadmor
#    Valeriu Smirichinski
#

# load all basic KIM make configuration
include ../Makefile.KIM_Config

# set model driver specific details
MODEL_DRIVER_NAME := MEAM_2NN__MD_111291751625_001
MODEL_NAME := MEAM_2NN_Fe_to_Ga__MO_145522277939_001
SPECIES_001_NAME    := Fe
SPECIES_002_NAME    := Cr
SPECIES_003_NAME    := Mo
SPECIES_004_NAME    := W
SPECIES_005_NAME    := V
SPECIES_006_NAME    := Nb
SPECIES_007_NAME    := Ta
SPECIES_008_NAME    := Mn
SPECIES_009_NAME    := Li
SPECIES_010_NAME    := Ni
SPECIES_011_NAME    := Pd
SPECIES_012_NAME    := Pt
SPECIES_013_NAME    := Cu
SPECIES_014_NAME    := Ag
SPECIES_015_NAME    := Au
SPECIES_016_NAME    := Al
SPECIES_017_NAME    := Pb
SPECIES_018_NAME    := C
SPECIES_019_NAME    := Si
SPECIES_020_NAME    := Ge
SPECIES_021_NAME    := Ti
SPECIES_022_NAME    := Zr
SPECIES_023_NAME    := Co
SPECIES_024_NAME    := Mg
SPECIES_025_NAME    := O
SPECIES_026_NAME    := N
SPECIES_027_NAME    := H
SPECIES_028_NAME    := In
SPECIES_029_NAME    := Ga
PARAM_FILE_001_NAME := eam_db.tdb

# APPEND to compiler option flag lists
#FFLAGS   +=
#CFLAGS   +=
#CXXFLAGS +=
#LDFLAGS  +=

# load remaining KIM make configuration
include $(KIM_DIR)/$(builddir)/Makefile.ParameterizedModel
